
spring:
  freemarker:
    check-template-location: false
  activiti:
    check-process-definitions: false
  liquibase:
    enabled: false
  jpa:
    properties:
      hibernate:
        cache:
          use_second_level_cache: false
    open-in-view: true
    generate-ddl: true # auto geno
  aop:
    proxy-target-class: false

#  jpa:
#    hibernate:
#      cache:
#        use_second_level_cache: false
server:
  port: 9999
  servlet:
    context-path: "/activiti-app"
